# for general tips : https://ealizadeh.com/blog/guide-to-python-env-pkg-dependency-using-conda-poetry
# install poetry : https://python-poetry.org/docs/
# add poetry to the PATH, run `poetry install` in conda env created by this file
# 0. remove old pycpt env: conda env remove -n pycpt
# 1. create env with python specified also in poetry: conda env create --file=conda_env_empty.yaml
# 2. activate pycpt
# 3. switch to PYCPT_HOME with pyproject.toml file
# 4. poetry install
name: sizing_calculator

channels:
  - conda-forge
  - default

dependencies:
  # must be consistent with pyproject.toml
  #  AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'? use python 3.11
  #  https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean
  - python>=3.11,<3.12
  - pip>=22.3.0,<22.4.0
