[tool.poetry]
name = "sizing_calculator"
version = "0.1.0"
description = "calculator for sizing of a k8s deploymnet."
authors = ["Bahnik, Tomas <tomas.bahnik@email.cz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
snowflake-connector-python = {extras = ["pandas"], version = "^3.6.0"}
snowflake-sqlalchemy = "^1.5.1"
typer = "^0.9.0"
pytest = "^7.4.4"
prometheus-pandas = "^0.3.3"
langchain = "^0.1.3"
# V2 dosn't support pd.Timestamp but pydantic-settings needs pydantic>=2.3.0
pydantic = "1.10.14"
openai = "^1.9.0"
pandasai = "1.5.3"
langchain-community = "^0.0.15"
