[tool.poetry]
name = "pycpt"
version = "0.1.0"
description = "Packages for pycpt with AI support"
authors = ["Bahnik, Tomas <tomas.bahnik@ataccama.com>"]
readme = "README.md"
# cpt\bin\pycpt\pycpt does not contain any element see
# https://stackoverflow.com/questions/75397736/poetry-install-on-an-existing-project-error-does-not-contain-any-element
# `poetry install --no-root` or remove the line below
#packages = [{include = "pycpt"}]

[tool.poetry.dependencies]
# Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
# For scipy, a possible solution would be to set the `python` property to ">=3.11,<3.13"
python = ">=3.11,<3.12"
# required by pandasai 0.7.2
pandas = "^1.5.3"
pandasai = "^0.7.2"
langchain = "^0.0.245"
marvin = "^1.2.1"
snowflake-connector-python = {extras = ["pandas"], version = "3.0.4"}
snowflake-sqlalchemy = "1.4.7"
flatten-dict = "^0.4.2"
ruyaml = "^0.91.0"
dpath = "^2.1.6"
psycopg2 = "^2.9.6"
prometheus-pandas = "^0.3.2"
prometheus-api-client = "^0.5.3"
tabulate = "^0.9.0"
scipy = "^1.11.1"
xarray = "^2023.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
