apiVersion: batch/v1
kind: CronJob
metadata:
  name: sc-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sc-container
              image: sizing-calculator:latest
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
