FROM_TIME_ALIAS = 'FROM_TIME'
TO_TIME_ALIAS = 'TO_TIME'
API_TESTS_CU_RUN_INFO_TABLE_NAME = 'API_TESTS_CU_RUN_INFO'.lower()
API_TESTS_CU_RAW_DATA_TABLE_NAME = 'API_TESTS_CU_RAW_DATA'.lower()
API_TESTS_CU_LIST_TABLE_NAME = 'API_TESTS_CU_LIST'.lower()
PERIOD_UTC_COLUMN = 'PERIOD_UTC'
DEFAULT_SCHEMA = 'API_TESTS'
