import os

DEFAULT_STEP_SEC = 30  # float in sec
DEFAULT_TIME_DELTA_HOURS = 1
DEFAULT_RATE_INTERVAL = '1m'
MIBS: int = 1024 ** 2
GIBS: int = 1024 ** 3
NON_EMPTY_LABEL = ".+"
PROMETHEUS_URL = os.getenv("PROMETHEUS_URL")
NAMESPACE_COLUMN = 'NAMESPACE'
POD_COLUMN = 'POD'
CONTAINER_COLUMN = 'CONTAINER'
TIMESTAMP_COLUMN = 'TIMESTAMP'
PORTAL_ONE_NS = "one.+"
DEFAULT_PORTAL_GRP_KEYS = [NAMESPACE_COLUMN.lower(), POD_COLUMN.lower(), CONTAINER_COLUMN.lower()]
POD_BASIC_RESOURCES_TABLE = 'POD_BASIC_RESOURCES'
JVM_BASIC_TABLE = 'PORTAL_JVM_BASIC'
